CREATE TABLE leads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    first_name VARCHAR(100) NULL,
    last_name VARCHAR(100) NULL,
    company_name VARCHAR(150) NULL,
    job_title VARCHAR(100) NULL,
    phone VARCHAR(30) NULL,
    mobile VARCHAR(30) NULL,
    email VARCHAR(150) NULL,
    website VARCHAR(150) NULL,
    city VARCHAR(100) NULL,
    province VARCHAR(100) NULL,
    source VARCHAR(50) NULL,
    channel VARCHAR(50) NULL,
    campaign VARCHAR(100) NULL,
    service_interest VARCHAR(100) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'nuevo',
    priority VARCHAR(20) NOT NULL DEFAULT 'media',
    temperature VARCHAR(20) NULL,
    next_action VARCHAR(255) NULL,
    notes_internal TEXT NULL,
    assigned_user_id INT UNSIGNED NULL,
    created_by INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_leads_assigned_user FOREIGN KEY (assigned_user_id) REFERENCES users(id),
    CONSTRAINT fk_leads_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);
